theme = "tophat"
title = "Zheng ShengYun's Blog"
baseURL = "https://example.com/"
languageCode = "en-us"
paginate = 5

[params]
    
  subtitle = "Zheng ShengYun's Blog"
  description = ""
  author = "郑盛允"

  main = "post"
  featured = true
  
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = true
  show_tags_on_article = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/pages/about/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/pages/contact/"    
  
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jupiterzheng29" 

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/gabrielzhen"